<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $courses = [
            'Computer Science',
            'Information Technology',
            'Software Engineering',
            'Business Administration',
            'Economics',
            'Accounting',
            'Finance',
            'Marketing',
            'Human Resource Management',
            'Law',
            'Medicine',
            'Nursing',
            'Pharmacy',
            'Dentistry',
            'Civil Engineering',
            'Electrical Engineering',
            'Mechanical Engineering',
            'Architecture',
            'Environmental Science',
            'Hospitality and Tourism Management',
            'Education',
            'Psychology',
            'Sociology',
            'Political Science',
            'Mathematics',
            'Statistics',
            'Biotechnology',
            'Public Health',
            'Graphic Design',
            'Journalism and Mass Communication',
            'Computer Engineering',
            'Network Engineering',
            'Cyber Security',
            'Data Science',
            'Artificial Intelligence',
            'Machine Learning',
            'Cloud Computing',
            'Information Systems',
            'Business Information Systems',
            'Health Informatics',
            'Software Development',
            'Systems Engineering',
            'Software Architecture',
            'Game Development',
            'Mobile Application Development',
            'Web Development',
            'Digital Media',
            'Animation',
            'Multimedia Design',
            'Industrial Design',
            'Product Design',
            'Interior Design',
            'Fashion Design',
            'Textile Design',
            'Fine Arts',
            'Music',
            'Performing Arts',
            'Graphic Communication',
            'Photography',
            'Film and Television Production',
            'Media Studies',
            'Public Relations',
            'Media and Communication',
            'Broadcasting',
            'Event Management',
            'Travel and Tourism',
            'Culinary Arts',
            'Restaurant Management',
            'Sports Management',
            'Exercise Science',
            'Physical Education',
            'Psychology of Education',
            'Guidance and Counseling',
            'Special Needs Education',
            'Early Childhood Education',
            'Adult Education',
            'Educational Administration',
            'Curriculum Development',
            'Quantitative Finance',
            'Actuarial Science',
            'Insurance and Risk Management',
            'Supply Chain Management',
            'Logistics and Transport',
            'Operations Management',
            'Project Management',
            'Entrepreneurship',
            'International Business',
            'Corporate Governance',
            'Microfinance',
            'Retail Management',
            'Commerce',
            'Banking and Finance',
            'Public Administration',
            'Development Studies',
            'Sustainable Development',
            'Environmental Management',
            'Natural Resource Management',
            'Wildlife Management',
            'Forestry',
            'Fisheries and Aquaculture',
            'Agricultural Science',
            'Agronomy',
            'Horticulture',
            'Animal Science',
            'Food Science and Technology',
            'Veterinary Medicine',
            'Geography',
            'Geology',
            'Geophysics',
            'Meteorology',
            'Earth Science',
            'Oceanography',
            'Biological Sciences',
            'Genetics',
            'Molecular Biology',
            'Microbiology',
            'Botany',
            'Zoology',
            'Environmental Health',
            'Occupational Health and Safety',
            'Biomedical Science',
            'Clinical Laboratory Science',
            'Radiography',
            'Physiotherapy',
            'Occupational Therapy',
            'Optometry',
            'Nutrition and Dietetics',
            'Speech and Language Therapy',
            'Logistics Management',
            'Quality Assurance',
            'Business Analytics',
            'E-commerce',
            'Blockchain Technology',
            'Internet of Things',
            'Embedded Systems',
            'Robotics',
            'Automotive Engineering',
            'Marine Engineering',
            'Petroleum Engineering',
            'Mining Engineering',
            'Environmental Engineering',
            'Chemical Engineering',
            'Biomedical Engineering',
            'Agricultural Engineering',
            'Surveying and Geomatics',
            'Urban and Regional Planning',
            'Landscape Architecture',
            'Real Estate Management',
        ];

        foreach ($courses as $name) {
            Course::firstOrCreate(
                ['name' => $name],
                ['level' => 'degree']
            );
        }
    }
}
