services:
  - type: web
    name: tariq
    env: docker
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    buildCommand: composer install --no-interaction --ignore-platform-reqs
    postBuildCommand: |
      mkdir -p database storage/framework/sessions storage/logs bootstrap/cache
      if [ "$DB_CONNECTION" = "sqlite" ]; then
        touch database/database.sqlite
      fi
      chmod -R 775 database storage bootstrap/cache
      php artisan config:cache
      php artisan optimize:clear
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'true'
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug
      - key: APP_URL
        value: 'https://tariq-1nqr.onrender.com'
      - key: OTP_DEV
        value: 'false'
      - key: SMS_PROVIDER
        value: 'infobip'
      - key: INFOBIP_API_KEY
        value: '7706195a2dec6be5acfc4828b0f41cd2-fa2f05d9-a603-48ce-9d60-a7b08c7f83a7'
      - key: INFOBIP_BASE_URL
        value: 'https://qwe862.api.infobip.com'
      - key: INFOBIP_FROM
        value: '+447491163443'
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_SECURE_COOKIE
        value: 'false'
      - key: SESSION_SAME_SITE
        value: lax
      - key: CACHE_DRIVER
        value: file
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: APP_KEY
        value: base64:7EXD3OMomubbovehVLk4WlGjzTkaZsULTBuJ8IcaL1U=
      - key: DB_SSLMODE
        value: prefer
      - key: ADMIN_EMAIL
        value: 'admin@tariq.go.tz'
    startCommand: |
      sh -lc "php artisan migrate --force && php artisan db:seed --force && exec apache2-foreground"
