services:
  - type: web
    name: tariq
    env: docker
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'
      - key: APP_URL
        value: 'https://tariq-lnqr.onrender.com'
      - key: LOG_CHANNEL
        value: stack
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_SECURE_COOKIE
        value: 'false'
      - key: SESSION_SAME_SITE
        value: lax
      - key: CACHE_DRIVER
        value: file
      - key: DB_CONNECTION
        value: sqlite
      - key: ADMIN_EMAIL
        value: 'admin@tariq.go.tz'
